apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels: 
    app: hello-world
spec:
  selectors:
    matchLabels:
      app: hello-world
  template:
    metadata:
     name: hello-world-pod
     labels:
      app: hello-world
    spec:
     containers:
      - name: hello-world
        image: danklofan/hello-world:latest
        containerPort: 80
  replicas: 1